-- ============================================
-- AlgoHub 算法知识库 数据库初始化脚本（完整版）
-- 覆盖：基础算法/搜索/数据结构/图论/DP/字符串/数学/思维
-- ============================================

DROP TABLE IF EXISTS `algorithms`;
DROP TABLE IF EXISTS `algorithm_categories`;

CREATE TABLE `algorithm_categories` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '分类ID',
    `name` VARCHAR(50) NOT NULL COMMENT '分类名称',
    `parent_id` BIGINT DEFAULT NULL COMMENT '父分类ID',
    `sort_order` INT DEFAULT 0 COMMENT '排序序号',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`parent_id`) REFERENCES `algorithm_categories`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='算法分类表';

CREATE TABLE `algorithms` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '算法ID',
    `title` VARCHAR(100) NOT NULL COMMENT '算法名称',
    `description` TEXT COMMENT '算法简介',
    `usage_intro` TEXT COMMENT '使用场景/用法说明',
    `cpp_template` TEXT COMMENT 'C++模板代码',
    `category_id` BIGINT DEFAULT NULL COMMENT '所属分类ID',
    `difficulty` VARCHAR(20) DEFAULT 'medium' COMMENT '难度：easy/medium/hard',
    `tags` VARCHAR(255) DEFAULT NULL COMMENT '标签，逗号分隔',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`category_id`) REFERENCES `algorithm_categories`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='算法详情表';

-- ============================================
-- 插入分类数据
-- ============================================
INSERT INTO `algorithm_categories` (`id`, `name`, `parent_id`, `sort_order`) VALUES
(1, '基础算法', NULL, 1),
(2, '搜索', NULL, 2),
(3, '数据结构', NULL, 3),
(4, '图论', NULL, 4),
(5, '动态规划', NULL, 5),
(6, '字符串', NULL, 6),
(7, '数学', NULL, 7),
(8, '思维技巧', NULL, 8);

INSERT INTO `algorithm_categories` (`name`, `parent_id`, `sort_order`) VALUES
('排序', 1, 1),('二分查找/三分查找', 1, 2),('贪心', 1, 3),('分治', 1, 4),
('双指针/滑动窗口', 1, 5),('前缀和与差分', 1, 6),('离散化', 1, 7),('位运算基础', 1, 8),
('DFS及剪枝', 2, 1),('BFS', 2, 2),('双向BFS', 2, 3),('回溯', 2, 4),
('并查集', 3, 1),('哈希表/滚动哈希', 3, 2),('单调栈/单调队列', 3, 3),('线段树', 3, 4),
('树状数组', 3, 5),('最近公共祖先(LCA)', 3, 6),('字典树(Trie)', 3, 7),('AC自动机', 3, 8),
('分块', 3, 9),('莫队算法', 3, 10),
('最小生成树', 4, 1),('最短路', 4, 2),('拓扑排序', 4, 3),('强连通分量(Tarjan)', 4, 4),
('割点/割边', 4, 5),('二分图判定', 4, 6),('二分图最大匹配', 4, 7),('欧拉路径/欧拉回路', 4, 8),
('差分约束系统', 4, 9),
('背包DP', 5, 1),('区间DP', 5, 2),('树形DP', 5, 3),('数位DP', 5, 4),
('状压DP', 5, 5),('计数DP', 5, 6),('概率DP', 5, 7),
('KMP算法', 6, 1),('Manacher算法', 6, 2),
('素数筛', 7, 1),('欧拉函数', 7, 2),('扩展欧几里得', 7, 3),('中国剩余定理', 7, 4),
('快速幂/矩阵快速幂', 7, 5),('组合数取模', 7, 6),('容斥原理', 7, 7),('博弈论', 7, 8),
('高斯消元', 7, 9),('线性基', 7, 10),
('模拟', 8, 1),('构造', 8, 2),('逆向思维', 8, 3);

-- ============================================
-- 算法数据（共68个算法，覆盖全部子分类）
-- 难度说明：easy=入门基础 medium=核心算法 hard=进阶/竞赛
-- ============================================

-- ==================== 基础算法 ====================

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('快速排序', '快速排序是一种基于分治思想的高效排序算法。选取基准元素(pivot)，将数组划分为小于和大于基准的两部分，递归排序。平均时间复杂度O(n log n)，最坏O(n²)。', '适用于大规模数据排序，C++ STL中std::sort的内部实现基础。不稳定排序，需要稳定排序时考虑归并排序。', '#include <vector>\nusing namespace std;\n\nint partition(vector<int>& arr, int low, int high) {\n    int pivot = arr[high];\n    int i = low - 1;\n    for (int j = low; j < high; j++) {\n        if (arr[j] <= pivot) {\n            i++;\n            swap(arr[i], arr[j]);\n        }\n    }\n    swap(arr[i + 1], arr[high]);\n    return i + 1;\n}\n\nvoid quickSort(vector<int>& arr, int low, int high) {\n    if (low < high) {\n        int pi = partition(arr, low, high);\n        quickSort(arr, low, pi - 1);\n        quickSort(arr, pi + 1, high);\n    }\n}', (SELECT id FROM algorithm_categories WHERE name='排序'), 'medium', '排序,分治'),

('归并排序', '稳定的分治排序算法。将数组递归分成两半，分别排序后合并。时间复杂度始终O(n log n)，需O(n)额外空间。', '适用于需要稳定排序的场景，以及链表排序（归并排序在链表上无需额外空间）。', '#include <vector>\nusing namespace std;\n\nvoid merge(vector<int>& arr, int l, int m, int r) {\n    int n1 = m - l + 1, n2 = r - m;\n    vector<int> L(n1), R(n2);\n    for (int i = 0; i < n1; i++) L[i] = arr[l + i];\n    for (int i = 0; i < n2; i++) R[i] = arr[m + 1 + i];\n    int i = 0, j = 0, k = l;\n    while (i < n1 && j < n2) {\n        if (L[i] <= R[j]) arr[k++] = L[i++];\n        else arr[k++] = R[j++];\n    }\n    while (i < n1) arr[k++] = L[i++];\n    while (j < n2) arr[k++] = R[j++];\n}\n\nvoid mergeSort(vector<int>& arr, int l, int r) {\n    if (l < r) {\n        int m = l + (r - l) / 2;\n        mergeSort(arr, l, m);\n        mergeSort(arr, m + 1, r);\n        merge(arr, l, m, r);\n    }\n}', (SELECT id FROM algorithm_categories WHERE name='排序'), 'medium', '排序,分治,稳定'),

('堆排序', '利用大顶堆数据结构进行排序。先建堆O(n)，反复取出堆顶元素放到数组末尾并调整，每次调整O(log n)。时间复杂度O(n log n)，空间复杂度O(1)，不稳定排序。', '适用于需要原地排序且对稳定性无要求的场景，常用于实现优先队列。', '#include <vector>\nusing namespace std;\n\nvoid heapify(vector<int>& arr, int n, int i) {\n    int largest = i, l = 2 * i + 1, r = 2 * i + 2;\n    if (l < n && arr[l] > arr[largest]) largest = l;\n    if (r < n && arr[r] > arr[largest]) largest = r;\n    if (largest != i) {\n        swap(arr[i], arr[largest]);\n        heapify(arr, n, largest);\n    }\n}\n\nvoid heapSort(vector<int>& arr) {\n    int n = arr.size();\n    for (int i = n / 2 - 1; i >= 0; i--) heapify(arr, n, i);\n    for (int i = n - 1; i > 0; i--) {\n        swap(arr[0], arr[i]);\n        heapify(arr, i, 0);\n    }\n}', (SELECT id FROM algorithm_categories WHERE name='排序'), 'medium', '排序,堆'),

('计数排序', '非比较排序算法，适用于数据范围较小的整数排序。统计每个值出现次数后按顺序输出。时间复杂度O(n+k)，k为数据范围。', '适用于整数排序且数据范围较小（如年龄、成绩排名等）。不适用于浮点数或范围很大的数据。', '#include <vector>\n#include <algorithm>\nusing namespace std;\n\nvoid countingSort(vector<int>& arr) {\n    if (arr.empty()) return;\n    int mx = *max_element(arr.begin(), arr.end());\n    int mn = *min_element(arr.begin(), arr.end());\n    int range = mx - mn + 1;\n    vector<int> count(range), output(arr.size());\n    for (int x : arr) count[x - mn]++;\n    for (int i = 1; i < range; i++) count[i] += count[i - 1];\n    for (int i = arr.size() - 1; i >= 0; i--) {\n        output[count[arr[i] - mn] - 1] = arr[i];\n        count[arr[i] - mn]--;\n    }\n    arr = output;\n}', (SELECT id FROM algorithm_categories WHERE name='排序'), 'easy', '排序,非比较排序'),

('二分查找', '在有序序列中每次将搜索范围减半来查找目标值。时间复杂度O(log n)。核心在于正确处理边界条件和循环不变量。', '最基础的高效搜索算法，适用于有序数组中的查找。变体：查找第一个/最后一个等于目标值的位置、查找插入位置等。', 'int binarySearch(vector<int>& arr, int target) {\n    int l = 0, r = arr.size() - 1;\n    while (l <= r) {\n        int mid = l + (r - l) / 2;\n        if (arr[mid] == target) return mid;\n        else if (arr[mid] < target) l = mid + 1;\n        else r = mid - 1;\n    }\n    return -1;\n}', (SELECT id FROM algorithm_categories WHERE name='二分查找/三分查找'), 'easy', '搜索,二分'),

('三分查找', '三分查找用于在单峰函数中寻找极值点。每次将区间分成三段，根据两个分点的函数值比较舍弃1/3区间，时间复杂度O(log n)。', '适用于凸函数/凹函数求极值，以及需要找到峰值的问题（如数组中寻找峰值元素）。', 'double ternarySearch(double l, double r, function<double(double)> f) {\n    const double EPS = 1e-9;\n    while (r - l > EPS) {\n        double m1 = l + (r - l) / 3;\n        double m2 = r - (r - l) / 3;\n        if (f(m1) < f(m2)) l = m1;\n        else r = m2;\n    }\n    return f(l);\n}', (SELECT id FROM algorithm_categories WHERE name='二分查找/三分查找'), 'medium', '搜索,三分');

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('贪心算法', '贪心算法在每一步选择中都采取当前状态下最优的选择，期望最终结果是全局最优。贪心策略不一定总能得到全局最优解，需要严格的数学证明。', '适用于具有贪心选择性质和最优子结构的问题，如活动安排、哈夫曼编码、最小生成树、部分背包问题等。', '#include <vector>\n#include <algorithm>\nusing namespace std;\n\n// 活动安排问题：选择最多不重叠的区间\nint activitySelection(vector<pair<int,int>>& intervals) {\n    sort(intervals.begin(), intervals.end(),\n         [](auto& a, auto& b) { return a.second < b.second; });\n    int cnt = 1, end = intervals[0].second;\n    for (int i = 1; i < intervals.size(); i++) {\n        if (intervals[i].first >= end) {\n            cnt++;\n            end = intervals[i].second;\n        }\n    }\n    return cnt;\n}', (SELECT id FROM algorithm_categories WHERE name='贪心'), 'easy', '基础算法,贪心'),

('分治算法', '分治算法将原问题分解为若干个规模较小但结构相似的子问题，递归求解子问题后合并结果。典型代表有归并排序、快速排序、二分查找等。核心三步骤：分解→解决→合并。', '适用于可分解为相似子问题的问题，如汉诺塔、棋盘覆盖、最近点对、FFT等。通常能将O(n²)优化到O(n log n)。', '#include <vector>\nusing namespace std;\n\n// 归并排序是分治的经典体现\nvoid mergeSort(vector<int>& arr, int l, int r) {\n    if (l >= r) return;  // 最小子问题\n    int mid = l + (r - l) / 2;\n    mergeSort(arr, l, mid);      // 分解并解决左半\n    mergeSort(arr, mid + 1, r);  // 分解并解决右半\n    // 合并两个有序子数组（merge函数略）\n}', (SELECT id FROM algorithm_categories WHERE name='分治'), 'medium', '基础算法,分治'),

('滑动窗口', '滑动窗口技术使用双指针维护一个连续区间（窗口），窗口大小固定或不固定。移动过程中增量更新窗口内信息，将O(n²)暴力枚举优化到O(n)。', '常用于字符串/数组的连续子串/子数组问题，如最长无重复字符子串、最小覆盖子串、和为定值的最短子数组等。', '#include <string>\n#include <unordered_map>\nusing namespace std;\n\n// 最长无重复字符子串\nint lengthOfLongestSubstring(string s) {\n    unordered_map<char, int> pos;\n    int left = 0, maxLen = 0;\n    for (int right = 0; right < s.size(); right++) {\n        if (pos.count(s[right]))\n            left = max(left, pos[s[right]] + 1);\n        pos[s[right]] = right;\n        maxLen = max(maxLen, right - left + 1);\n    }\n    return maxLen;\n}', (SELECT id FROM algorithm_categories WHERE name='双指针/滑动窗口'), 'medium', '基础算法,双指针,滑动窗口'),

('前缀和与差分', '前缀和：预处理数组前i项的和，使得任意区间和可在O(1)内查询。差分：前缀和的逆运算，用于高效区间修改（区间加减后O(1)标记，最后前缀和还原）。', '前缀和适用于频繁区间求和查询；差分适用于频繁区间增减操作。两者常结合使用处理二维矩阵问题。', '#include <vector>\nusing namespace std;\n\n// 一维前缀和\nvector<int> prefixSum(vector<int>& arr) {\n    int n = arr.size();\n    vector<int> pre(n + 1, 0);\n    for (int i = 0; i < n; i++)\n        pre[i + 1] = pre[i] + arr[i];\n    return pre; // pre[r+1] - pre[l] = sum[l..r]\n}\n\n// 一维差分：区间[l,r]加val\nvoid diffAdd(vector<int>& diff, int l, int r, int val) {\n    diff[l] += val;\n    if (r + 1 < diff.size()) diff[r + 1] -= val;\n}', (SELECT id FROM algorithm_categories WHERE name='前缀和与差分'), 'easy', '基础算法,前缀和,差分'),

('离散化', '离散化将大范围稀疏数据映射到连续的较小范围内，保持元素间的相对大小关系不变。通常结合排序+去重+二分查找实现。', '适用于数据值域很大但数量较少的场景，如"求逆序对"中元素值可能达到10^9但数量只有10^5。常与树状数组/线段树配合使用。', '#include <vector>\n#include <algorithm>\nusing namespace std;\n\nvector<int> discretize(vector<int>& arr) {\n    vector<int> sorted = arr;\n    sort(sorted.begin(), sorted.end());\n    sorted.erase(unique(sorted.begin(), sorted.end()), sorted.end());\n    vector<int> res(arr.size());\n    for (int i = 0; i < arr.size(); i++)\n        res[i] = lower_bound(sorted.begin(), sorted.end(), arr[i]) - sorted.begin() + 1;\n    return res; // 映射到1-based索引\n}', (SELECT id FROM algorithm_categories WHERE name='离散化'), 'easy', '基础算法,离散化'),

('位运算基础', '位运算直接在二进制位上操作，包括：与(&)、或(|)、异或(^)、取反(~)、左移(<<)、右移(>>)。常用技巧包括lowbit、状态压缩、快速判断奇偶等。', '用于状态压缩DP、权限管理（位掩码）、哈希、算法优化（如n&(n-1)消除最低位1）等场景，效率极高。', '// 常用位运算技巧\nint lowbit(int x) { return x & -x; }           // 取最低位1\nbool isPowerOfTwo(int x) { return x > 0 && (x & (x - 1)) == 0; }\nint countOnes(int x) {                           // 统计二进制中1的个数\n    int cnt = 0;\n    while (x) { x &= x - 1; cnt++; }\n    return cnt;\n}\nbool isOdd(int x) { return x & 1; }              // 判断奇偶\nint swap(int& a, int& b) { a ^= b; b ^= a; a ^= b; } // 异或交换', (SELECT id FROM algorithm_categories WHERE name='位运算基础'), 'easy', '基础算法,位运算');

-- ==================== 搜索 ====================

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('DFS及剪枝', '深度优先搜索(DFS)从起点出发沿一条路径深入到底，然后回溯探索其他分支。剪枝是在搜索过程中提前排除不可能产生最优解的分支，大幅提升效率。', '适用于全排列、组合、子集、图的连通性判断、路径搜索等问题。剪枝常用于竞赛中的搜索优化（如最优性剪枝、可行性剪枝）。', '#include <vector>\nusing namespace std;\n\nvector<vector<int>> adj;\nvector<bool> visited;\n\nvoid dfs(int u) {\n    visited[u] = true;\n    for (int v : adj[u])\n        if (!visited[v]) dfs(v);\n}\n\n// 回溯框架（以全排列为例）\nvoid backtrack(vector<int>& nums, vector<bool>& used,\n               vector<int>& cur, vector<vector<int>>& res) {\n    if (cur.size() == nums.size()) {\n        res.push_back(cur);\n        return;\n    }\n    for (int i = 0; i < nums.size(); i++) {\n        if (used[i]) continue;\n        if (i > 0 && nums[i] == nums[i-1] && !used[i-1]) continue;\n        used[i] = true; cur.push_back(nums[i]);\n        backtrack(nums, used, cur, res);\n        cur.pop_back(); used[i] = false;\n    }\n}', (SELECT id FROM algorithm_categories WHERE name='DFS及剪枝'), 'medium', '搜索,DFS,剪枝,回溯'),

('BFS', '广度优先搜索(BFS)逐层遍历，从起点开始先访问所有相邻节点，再访问相邻节点的相邻节点。使用队列实现，保证找到的路径最短（边权为1）。', '适用于最短路径（无权图）、层序遍历、连通分量标记、状态空间搜索（如八数码问题）等。', '#include <queue>\n#include <vector>\nusing namespace std;\n\nvoid bfs(int start, vector<vector<int>>& adj) {\n    int n = adj.size();\n    vector<bool> visited(n, false);\n    vector<int> dist(n, -1);\n    queue<int> q;\n    q.push(start);\n    visited[start] = true; dist[start] = 0;\n    while (!q.empty()) {\n        int u = q.front(); q.pop();\n        for (int v : adj[u])\n            if (!visited[v]) {\n                visited[v] = true;\n                dist[v] = dist[u] + 1;\n                q.push(v);\n            }\n    }\n}', (SELECT id FROM algorithm_categories WHERE name='BFS'), 'medium', '搜索,BFS'),

('双向BFS', '双向BFS从起点和终点同时进行BFS，当两个搜索相遇时即找到最短路径。相比单向BFS可将搜索空间从O(b^d)降至O(b^(d/2))。', '适用于已知起点和终点的最短路径问题（如单词接龙、八数码），搜索空间巨大但深度较浅时效果显著，实现复杂度较高。', '#include <queue>\n#include <unordered_set>\nusing namespace std;\n\nint bidirectionalBFS(string start, string end,\n    function<vector<string>(string)> getNext) {\n    unordered_set<string> s1{start}, s2{end};\n    unordered_set<string> visited{start, end};\n    int step = 0;\n    while (!s1.empty() && !s2.empty()) {\n        if (s1.size() > s2.size()) swap(s1, s2);\n        unordered_set<string> next;\n        for (auto& cur : s1)\n            for (auto& nxt : getNext(cur)) {\n                if (s2.count(nxt)) return step + 1;\n                if (!visited.count(nxt)) {\n                    visited.insert(nxt); next.insert(nxt);\n                }\n            }\n        s1 = next; step++;\n    }\n    return -1;\n}', (SELECT id FROM algorithm_categories WHERE name='双向BFS'), 'hard', '搜索,BFS,双向BFS'),

('回溯', '回溯算法系统地搜索问题的所有解或最优解。当探索到某一步发现当前选择不可能产生有效解时，退回上一步重新选择。本质是深度优先的"试错"搜索。', '适用于组合、排列、子集、棋盘问题（N皇后、数独）、图的着色、哈密顿回路等需要枚举所有可能解的问题。', '#include <vector>\nusing namespace std;\n\n// N皇后问题\nvoid solve(int row, int n, vector<int>& pos,\n    vector<bool>& d1, vector<bool>& d2,\n    vector<vector<string>>& res) {\n    if (row == n) {\n        vector<string> board(n, string(n, ''.''));\n        for (int i = 0; i < n; i++) board[i][pos[i]] = ''Q'';\n        res.push_back(board); return;\n    }\n    for (int col = 0; col < n; col++) {\n        if (pos[col] != -1) continue; // 列冲突\n        if (d1[row + col] || d2[row - col + n - 1]) continue;\n        pos[col] = row;\n        d1[row + col] = d2[row - col + n - 1] = true;\n        solve(row + 1, n, pos, d1, d2, res);\n        pos[col] = -1;\n        d1[row + col] = d2[row - col + n - 1] = false;\n    }\n}', (SELECT id FROM algorithm_categories WHERE name='回溯'), 'medium', '搜索,回溯,DFS,N皇后');

-- ==================== 数据结构 ====================

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('并查集', '并查集(DSU)用于管理元素分组。支持Find（查找所属集合）和Union（合并两个集合）。通过路径压缩和按秩合并优化后均摊复杂度接近O(1)。', '广泛应用于连通性问题（Kruskal最小生成树、图的连通分量）、动态连通性判断、等价关系维护等。', '#include <vector>\nusing namespace std;\n\nclass DSU {\n    vector<int> parent, rank;\npublic:\n    DSU(int n) {\n        parent.resize(n); rank.resize(n, 0);\n        for (int i = 0; i < n; i++) parent[i] = i;\n    }\n    int find(int x) {\n        if (parent[x] != x) parent[x] = find(parent[x]);\n        return parent[x];\n    }\n    void unite(int x, int y) {\n        int px = find(x), py = find(y);\n        if (px == py) return;\n        if (rank[px] < rank[py]) parent[px] = py;\n        else if (rank[px] > rank[py]) parent[py] = px;\n        else { parent[py] = px; rank[px]++; }\n    }\n    bool same(int x, int y) { return find(x) == find(y); }\n};', (SELECT id FROM algorithm_categories WHERE name='并查集'), 'medium', '数据结构,并查集'),

('字符串哈希/滚动哈希', '字符串哈希将字符串映射为一个整数（模大质数），使得相同字符串的哈希值相同。滚动哈希利用滑动窗口在O(1)内从当前哈希值计算相邻子串哈希值。', '适用于字符串匹配（Rabin-Karp算法）、最长重复子串、回文子串判断等。相比KMP更灵活，可处理多模式串和二维匹配。', '#include <string>\nusing namespace std;\nusing ull = unsigned long long;\nconst ull BASE = 131;\n\nvector<ull> prehash, powbase;\nvoid init(string& s) {\n    int n = s.size();\n    prehash.resize(n + 1, 0); powbase.resize(n + 1, 1);\n    for (int i = 0; i < n; i++) {\n        prehash[i + 1] = prehash[i] * BASE + s[i];\n        powbase[i + 1] = powbase[i] * BASE;\n    }\n}\null getHash(int l, int r) {\n    return prehash[r + 1] - prehash[l] * powbase[r - l + 1];\n}', (SELECT id FROM algorithm_categories WHERE name='哈希表/滚动哈希'), 'medium', '数据结构,哈希,字符串,RabinKarp'),

('单调栈', '单调栈内元素保持单调递增或递减。当新元素破坏单调性时弹出栈顶直到恢复单调性。每个元素最多入栈出栈一次，O(n)。', '经典应用：下一个更大/更小元素（Next Greater Element）、柱状图中最大矩形面积、接雨水问题等。', '#include <vector>\n#include <stack>\nusing namespace std;\n\nvector<int> nextGreaterElement(vector<int>& nums) {\n    int n = nums.size();\n    vector<int> res(n, -1);\n    stack<int> st;\n    for (int i = 0; i < n; i++) {\n        while (!st.empty() && nums[st.top()] < nums[i])\n            res[st.top()] = nums[i], st.pop();\n        st.push(i);\n    }\n    return res;\n}', (SELECT id FROM algorithm_categories WHERE name='单调栈/单调队列'), 'medium', '数据结构,单调栈'),

('单调队列', '单调队列维护一个双端队列，队内元素保持单调性。滑动窗口时队首过期出队，队尾比新元素"差"的元素出队。每个元素最多入队出队一次，O(n)。', '最经典应用是求滑动窗口内的最大值/最小值。也可用于优化DP（如单调队列优化的背包问题）。', '#include <deque>\n#include <vector>\nusing namespace std;\n\nvector<int> maxSlidingWindow(vector<int>& nums, int k) {\n    deque<int> dq;\n    vector<int> res;\n    for (int i = 0; i < nums.size(); i++) {\n        while (!dq.empty() && dq.front() <= i - k) dq.pop_front();\n        while (!dq.empty() && nums[dq.back()] <= nums[i]) dq.pop_back();\n        dq.push_back(i);\n        if (i >= k - 1) res.push_back(nums[dq.front()]);\n    }\n    return res;\n}', (SELECT id FROM algorithm_categories WHERE name='单调栈/单调队列'), 'medium', '数据结构,单调队列,滑动窗口'),

('线段树', '线段树是一种二叉树形数据结构，每个节点代表一个区间，支持O(log n)的区间修改和区间查询。通过Lazy标记实现高效的区间更新。', '适用于频繁区间操作的问题：区间求和、区间最值、区间加法/乘法。配合离散化可处理10^9范围的区间问题。', '#include <vector>\nusing namespace std;\nusing ll = long long;\n\nclass SegTree {\n    vector<ll> tree, lazy;\n    int n;\n    void build(int node, int l, int r, vector<ll>& arr) {\n        if (l == r) { tree[node] = arr[l]; return; }\n        int mid = (l + r) / 2;\n        build(node * 2, l, mid, arr);\n        build(node * 2 + 1, mid + 1, r, arr);\n        tree[node] = tree[node * 2] + tree[node * 2 + 1];\n    }\n    void push(int node, int l, int r) {\n        if (lazy[node]) {\n            tree[node] += lazy[node] * (r - l + 1);\n            if (l != r) {\n                lazy[node * 2] += lazy[node];\n                lazy[node * 2 + 1] += lazy[node];\n            }\n            lazy[node] = 0;\n        }\n    }\n    void update(int node, int l, int r, int ql, int qr, ll val) {\n        push(node, l, r);\n        if (ql > r || qr < l) return;\n        if (ql <= l && r <= qr) { lazy[node] += val; push(node, l, r); return; }\n        int mid = (l + r) / 2;\n        update(node * 2, l, mid, ql, qr, val);\n        update(node * 2 + 1, mid + 1, r, ql, qr, val);\n        tree[node] = tree[node * 2] + tree[node * 2 + 1];\n    }\n    ll query(int node, int l, int r, int ql, int qr) {\n        push(node, l, r);\n        if (ql > r || qr < l) return 0;\n        if (ql <= l && r <= qr) return tree[node];\n        int mid = (l + r) / 2;\n        return query(node * 2, l, mid, ql, qr)\n             + query(node * 2 + 1, mid + 1, r, ql, qr);\n    }\npublic:\n    SegTree(vector<ll>& arr) {\n        n = arr.size();\n        tree.resize(4 * n); lazy.resize(4 * n);\n        build(1, 0, n - 1, arr);\n    }\n    void update(int l, int r, ll val) { update(1, 0, n - 1, l, r, val); }\n    ll query(int l, int r) { return query(1, 0, n - 1, l, r); }\n};', (SELECT id FROM algorithm_categories WHERE name='线段树'), 'hard', '数据结构,线段树,区间操作,Lazy标记'),

('树状数组', '树状数组(BIT/Fenwick Tree)维护前缀信息的数据结构。支持O(log n)的单点更新和区间查询，实现比线段树简洁。', '适用于前缀和/前缀最值维护，经典应用包括求逆序对。比线段树常数更小，但一般只能处理前缀信息。', '#include <vector>\nusing namespace std;\n\nclass BIT {\n    vector<int> tree;\n    int n;\npublic:\n    BIT(int n) : n(n) { tree.resize(n + 1); }\n    void add(int idx, int val) {\n        for (; idx <= n; idx += idx & -idx)\n            tree[idx] += val;\n    }\n    int sum(int idx) {\n        int s = 0;\n        for (; idx > 0; idx -= idx & -idx) s += tree[idx];\n        return s;\n    }\n    int rangeSum(int l, int r) { return sum(r) - sum(l - 1); }\n};', (SELECT id FROM algorithm_categories WHERE name='树状数组'), 'medium', '数据结构,树状数组,BIT'),

('最近公共祖先(LCA)', 'LCA求树上两个节点的最近公共祖先。倍增法预处理每个节点向上2^j步的祖先，查询时先跳到同深度再一起向上跳。预处理O(n log n)，查询O(log n)。', '广泛应用于树上两点间距离、树上差分、树链剖分等树上问题。竞赛中最常用倍增法和Tarjan离线算法。', '#include <vector>\nusing namespace std;\n\nconst int MAXN = 1e5, LOG = 17;\nvector<int> adj[MAXN];\nint up[MAXN][LOG + 1], depth[MAXN];\n\nvoid dfs(int u, int p) {\n    up[u][0] = p;\n    for (int j = 1; j <= LOG; j++)\n        up[u][j] = up[up[u][j-1]][j-1];\n    for (int v : adj[u]) {\n        if (v == p) continue;\n        depth[v] = depth[u] + 1;\n        dfs(v, u);\n    }\n}\n\nint lca(int u, int v) {\n    if (depth[u] < depth[v]) swap(u, v);\n    int diff = depth[u] - depth[v];\n    for (int j = 0; j <= LOG; j++)\n        if (diff & (1 << j)) u = up[u][j];\n    if (u == v) return u;\n    for (int j = LOG; j >= 0; j--)\n        if (up[u][j] != up[v][j])\n            u = up[u][j], v = up[v][j];\n    return up[u][0];\n}', (SELECT id FROM algorithm_categories WHERE name='最近公共祖先(LCA)'), 'hard', '数据结构,树,LCA,倍增'),

('字典树(Trie)', 'Trie（前缀树）用于高效存储和检索字符串集合。每个节点代表一个字符，从根到某节点的路径对应一个字符串前缀。查询复杂度O(L)，L为字符串长度。', '适用于字符串前缀匹配、自动补全、拼写检查、IP路由最长前缀匹配、异或最大值查询（01Trie）等。', '#include <string>\n#include <vector>\nusing namespace std;\n\nclass Trie {\n    struct Node {\n        vector<Node*> child;\n        bool isEnd;\n        Node() : child(26, nullptr), isEnd(false) {}\n    };\n    Node* root;\npublic:\n    Trie() { root = new Node(); }\n    void insert(string& word) {\n        Node* cur = root;\n        for (char c : word) {\n            int idx = c - ''a'';\n            if (!cur->child[idx]) cur->child[idx] = new Node();\n            cur = cur->child[idx];\n        }\n        cur->isEnd = true;\n    }\n    bool search(string& word) {\n        Node* cur = root;\n        for (char c : word) {\n            int idx = c - ''a'';\n            if (!cur->child[idx]) return false;\n            cur = cur->child[idx];\n        }\n        return cur->isEnd;\n    }\n};', (SELECT id FROM algorithm_categories WHERE name='字典树(Trie)'), 'medium', '数据结构,Trie,字符串'),

('AC自动机', 'AC自动机将Trie树与KMP的失配指针思想结合，实现多模式串的同时匹配。先构建Trie树，再通过BFS构建fail指针，匹配时沿fail指针转移。', '适用于多模式串匹配（同时查找多个关键词），如敏感词过滤、DNA序列匹配、搜索提示等。', '#include <queue>\n#include <string>\n#include <vector>\nusing namespace std;\n\nconst int ALP = 26;\nstruct Node { vector<int> next; int fail, cnt; Node() : next(ALP, 0), fail(0), cnt(0) {} };\nvector<Node> trie(1);\n\nvoid insert(string& s) {\n    int u = 0;\n    for (char c : s) {\n        int idx = c - ''a'';\n        if (!trie[u].next[idx]) {\n            trie[u].next[idx] = trie.size();\n            trie.emplace_back();\n        }\n        u = trie[u].next[idx];\n    }\n    trie[u].cnt++;\n}\n\nvoid build() {\n    queue<int> q;\n    for (int i = 0; i < ALP; i++)\n        if (trie[0].next[i]) q.push(trie[0].next[i]);\n    while (!q.empty()) {\n        int u = q.front(); q.pop();\n        for (int i = 0; i < ALP; i++) {\n            int& v = trie[u].next[i];\n            if (v) {\n                trie[v].fail = trie[trie[u].fail].next[i];\n                trie[v].cnt += trie[trie[v].fail].cnt;\n                q.push(v);\n            } else v = trie[trie[u].fail].next[i];\n        }\n    }\n}\n\nint query(string& s) {\n    int u = 0, ans = 0;\n    for (char c : s) {\n        u = trie[u].next[c - ''a''];\n        ans += trie[u].cnt;\n    }\n    return ans;\n}', (SELECT id FROM algorithm_categories WHERE name='AC自动机'), 'hard', '数据结构,字符串,AC自动机,多模式匹配'),

('分块（根号分治）', '分块将序列分成大小为√n的块，每块维护聚合信息。查询和修改时完整块整块操作，不完整块暴力操作，每操作O(√n)。', '适用于线段树复杂但需要区间操作的场景，在竞赛中作为"暴力数据结构"快速实现。也用于"根号分治"思想解决复杂问题。', '#include <vector>\n#include <cmath>\nusing namespace std;\nusing ll = long long;\n\nclass BlockArray {\n    int n, blockSize, blockCnt;\n    vector<ll> arr, blockSum;\npublic:\n    BlockArray(vector<ll>& a) {\n        n = a.size(); blockSize = sqrt(n);\n        blockCnt = (n + blockSize - 1) / blockSize;\n        arr = a; blockSum.assign(blockCnt, 0);\n        for (int i = 0; i < n; i++) blockSum[i / blockSize] += arr[i];\n    }\n    void update(int idx, ll val) {\n        blockSum[idx / blockSize] += val - arr[idx];\n        arr[idx] = val;\n    }\n    ll query(int l, int r) {\n        ll sum = 0;\n        int bl = l / blockSize, br = r / blockSize;\n        if (bl == br) {\n            for (int i = l; i <= r; i++) sum += arr[i];\n        } else {\n            for (int i = l; i < (bl + 1) * blockSize; i++) sum += arr[i];\n            for (int b = bl + 1; b < br; b++) sum += blockSum[b];\n            for (int i = br * blockSize; i <= r; i++) sum += arr[i];\n        }\n        return sum;\n    }\n};', (SELECT id FROM algorithm_categories WHERE name='分块'), 'medium', '数据结构,分块,根号算法'),

('莫队算法', '莫队算法离线处理区间查询问题。将所有查询按左端点所在块排序，同一块内按右端点排序，用双指针在区间间移动并增量更新答案。复杂度约O(n√n)。', '适用于可离线的区间统计问题（区间不同元素个数、区间众数等），以及不易用线段树维护的区间信息。', '#include <vector>\n#include <algorithm>\n#include <cmath>\nusing namespace std;\n\nstruct Query { int l, r, idx; };\n\nvector<int> moAlgorithm(vector<int>& arr, vector<Query>& queries) {\n    int n = arr.size(), q = queries.size();\n    int block = sqrt(n);\n    sort(queries.begin(), queries.end(), [&](Query& a, Query& b) {\n        if (a.l / block != b.l / block) return a.l / block < b.l / block;\n        return (a.l / block) & 1 ? a.r < b.r : a.r > b.r;\n    });\n    vector<int> res(q);\n    int curL = 0, curR = -1, curAns = 0;\n    auto add = [&](int pos) { /* 添加元素逻辑 */ };\n    auto remove = [&](int pos) { /* 移除元素逻辑 */ };\n    for (auto& q : queries) {\n        while (curL > q.l) add(--curL);\n        while (curR < q.r) add(++curR);\n        while (curL < q.l) remove(curL++);\n        while (curR > q.r) remove(curR--);\n        res[q.idx] = curAns;\n    }\n    return res;\n}', (SELECT id FROM algorithm_categories WHERE name='莫队算法'), 'hard', '数据结构,莫队,离线查询,根号算法');

-- ==================== 图论 ====================

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('Kruskal最小生成树', 'Kruskal算法按边权从小到大排序，用并查集判断是否成环，贪心选择不成环的边加入生成树。时间复杂度O(E log E)，适合稀疏图。', '适用于稀疏图的最小生成树问题。搭配并查集判断连通性。稠密图推荐使用Prim算法。', '#include <vector>\n#include <algorithm>\nusing namespace std;\n\nstruct Edge { int u, v, w; };\n\nint kruskal(int n, vector<Edge>& edges) {\n    sort(edges.begin(), edges.end(),\n         [](Edge& a, Edge& b) { return a.w < b.w; });\n    DSU dsu(n);\n    int mstWeight = 0, cnt = 0;\n    for (auto& e : edges) {\n        if (!dsu.same(e.u, e.v)) {\n            dsu.unite(e.u, e.v);\n            mstWeight += e.w; cnt++;\n            if (cnt == n - 1) break;\n        }\n    }\n    return cnt == n - 1 ? mstWeight : -1;\n}', (SELECT id FROM algorithm_categories WHERE name='最小生成树'), 'medium', '图论,MST,Kruskal,并查集'),

('Prim最小生成树', 'Prim算法从任意节点开始，每次选择与当前生成树距离最近的节点加入，类似Dijkstra的贪心策略。朴素O(V²)，优先队列优化O((V+E) log V)，适合稠密图。', '适用于稠密图的最小生成树问题（朴素Prim O(V²)在稠密图上比Kruskal O(E log E)更快）。', '#include <queue>\n#include <vector>\nusing namespace std;\nusing pii = pair<int, int>;\n\nint prim(int n, vector<vector<pii>>& adj) {\n    vector<bool> visited(n, false);\n    priority_queue<pii, vector<pii>, greater<pii>> pq;\n    pq.push({0, 0});\n    int mstWeight = 0, cnt = 0;\n    while (!pq.empty()) {\n        auto [w, u] = pq.top(); pq.pop();\n        if (visited[u]) continue;\n        visited[u] = true;\n        mstWeight += w; cnt++;\n        for (auto [v, nw] : adj[u])\n            if (!visited[v]) pq.push({nw, v});\n    }\n    return cnt == n ? mstWeight : -1;\n}', (SELECT id FROM algorithm_categories WHERE name='最小生成树'), 'medium', '图论,MST,Prim'),

('Dijkstra最短路', 'Dijkstra算法求解单源非负权最短路径。使用优先队列优化，时间复杂度O((V+E) log V)。核心：每次选择当前距离最小的未处理节点进行松弛。', '最常用的最短路算法，适用于非负权图。不能处理负权边—负权边应用Bellman-Ford或SPFA。', '#include <queue>\n#include <vector>\nusing namespace std;\nusing pii = pair<int, int>;\n\nvector<int> dijkstra(int n, vector<vector<pii>>& adj, int start) {\n    vector<int> dist(n, INT_MAX);\n    priority_queue<pii, vector<pii>, greater<pii>> pq;\n    dist[start] = 0; pq.push({0, start});\n    while (!pq.empty()) {\n        auto [d, u] = pq.top(); pq.pop();\n        if (d > dist[u]) continue;\n        for (auto [v, w] : adj[u]) {\n            if (dist[v] > dist[u] + w) {\n                dist[v] = dist[u] + w;\n                pq.push({dist[v], v});\n            }\n        }\n    }\n    return dist;\n}', (SELECT id FROM algorithm_categories WHERE name='最短路'), 'medium', '图论,最短路,Dijkstra,贪心'),

('Bellman-Ford最短路', 'Bellman-Ford算法求解含负权边的最短路，并能检测负环。进行V-1轮松弛操作，每轮遍历所有边。若第V轮仍能松弛则存在负环。O(VE)。', '适用于含负权边的一般图最短路，或需要检测负环的场景。非负权图用Dijkstra更高效。', '#include <vector>\nusing namespace std;\n\nstruct Edge { int u, v, w; };\n\nvector<int> bellmanFord(int n, vector<Edge>& edges, int start) {\n    vector<int> dist(n, INT_MAX);\n    dist[start] = 0;\n    for (int i = 0; i < n - 1; i++) {\n        bool updated = false;\n        for (auto& e : edges)\n            if (dist[e.u] != INT_MAX && dist[e.v] > dist[e.u] + e.w)\n                dist[e.v] = dist[e.u] + e.w, updated = true;\n        if (!updated) break;\n    }\n    for (auto& e : edges)\n        if (dist[e.u] != INT_MAX && dist[e.v] > dist[e.u] + e.w)\n            return {}; // 存在负环\n    return dist;\n}', (SELECT id FROM algorithm_categories WHERE name='最短路'), 'medium', '图论,最短路,Bellman-Ford,负权,负环'),

('Floyd最短路', 'Floyd算法求解任意两点间最短路径（全源最短路）。三重循环DP：dp[k][i][j]表示经过前k个节点时i到j的最短路。O(V³)，适合小图。', '适用于节点数较少（V≤500）的全源最短路问题，以及传递闭包、最小环等问题。', '#include <vector>\nusing namespace std;\n\nvoid floyd(vector<vector<int>>& dist) {\n    int n = dist.size();\n    for (int k = 0; k < n; k++)\n        for (int i = 0; i < n; i++)\n            for (int j = 0; j < n; j++)\n                if (dist[i][k] != INT_MAX && dist[k][j] != INT_MAX)\n                    dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]);\n}', (SELECT id FROM algorithm_categories WHERE name='最短路'), 'medium', '图论,最短路,Floyd,全源,DP'),

('SPFA最短路', 'SPFA是Bellman-Ford的队列优化版本：只将距离被更新的节点入队进行松弛。最坏O(VE)，但实际运行通常很快。可以处理负权边和检测负环。', '适用于含负权边的最短路（比Dijkstra慢但适用范围广），以及差分约束系统的求解。已被证明最坏情况下可能很慢，竞赛中要谨慎使用。', '#include <queue>\n#include <vector>\nusing namespace std;\n\nvector<int> spfa(int n, vector<vector<pair<int,int>>>& adj, int start) {\n    vector<int> dist(n, INT_MAX), cnt(n, 0);\n    vector<bool> inQueue(n, false);\n    queue<int> q;\n    dist[start] = 0; q.push(start); inQueue[start] = true;\n    while (!q.empty()) {\n        int u = q.front(); q.pop(); inQueue[u] = false;\n        for (auto [v, w] : adj[u]) {\n            if (dist[v] > dist[u] + w) {\n                dist[v] = dist[u] + w;\n                if (!inQueue[v]) {\n                    q.push(v); inQueue[v] = true;\n                    if (++cnt[v] > n) return {}; // 负环\n                }\n            }\n        }\n    }\n    return dist;\n}', (SELECT id FROM algorithm_categories WHERE name='最短路'), 'medium', '图论,最短路,SPFA,负权'),

('拓扑排序', '拓扑排序将有向无环图(DAG)的顶点排成线性序列，使对任意边(u,v)，u在序列中出现在v之前。Kahn算法(BFS+入度)实现，O(V+E)。', '用于任务调度（先修课问题）、依赖解析（Makefile构建顺序）、编译器指令排序等。', '#include <vector>\n#include <queue>\nusing namespace std;\n\nvector<int> topologicalSort(int n, vector<vector<int>>& adj) {\n    vector<int> indegree(n, 0);\n    for (int u = 0; u < n; u++)\n        for (int v : adj[u]) indegree[v]++;\n    queue<int> q;\n    for (int i = 0; i < n; i++)\n        if (indegree[i] == 0) q.push(i);\n    vector<int> order;\n    while (!q.empty()) {\n        int u = q.front(); q.pop();\n        order.push_back(u);\n        for (int v : adj[u])\n            if (--indegree[v] == 0) q.push(v);\n    }\n    return order.size() == n ? order : vector<int>();\n}', (SELECT id FROM algorithm_categories WHERE name='拓扑排序'), 'medium', '图论,拓扑排序,DAG');

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('强连通分量(Tarjan)', 'Tarjan算法用一次DFS求有向图所有强连通分量(SCC)。利用dfn（时间戳）和low（最早回溯节点），当dfn[u]==low[u]时栈中u及以上节点构成一个SCC。O(V+E)。', '用于有向图SCC分解，是2-SAT问题、缩点建DAG等图论问题的基础。', '#include <vector>\nusing namespace std;\n\nvoid tarjan(int u, vector<vector<int>>& adj,\n            vector<int>& dfn, vector<int>& low,\n            vector<bool>& inStack, vector<int>& stk,\n            int& timer, vector<vector<int>>& sccs) {\n    dfn[u] = low[u] = ++timer;\n    stk.push_back(u); inStack[u] = true;\n    for (int v : adj[u]) {\n        if (!dfn[v]) {\n            tarjan(v, adj, dfn, low, inStack, stk, timer, sccs);\n            low[u] = min(low[u], low[v]);\n        } else if (inStack[v])\n            low[u] = min(low[u], dfn[v]);\n    }\n    if (dfn[u] == low[u]) {\n        vector<int> scc; int v;\n        do {\n            v = stk.back(); stk.pop_back();\n            inStack[v] = false; scc.push_back(v);\n        } while (v != u);\n        sccs.push_back(scc);\n    }\n}', (SELECT id FROM algorithm_categories WHERE name='强连通分量(Tarjan)'), 'hard', '图论,SCC,Tarjan'),

('割点/割边(Tarjan)', '使用Tarjan算法的dfn/low数组求无向图中的割点（删除后图不连通）和割边/桥。判断条件：割点—low[v]>=dfn[u]（非根）/根有多子树；割边—low[v]>dfn[u]。O(V+E)。', '用于分析网络的脆弱性、关键节点检测等。在网络可靠性分析、交通网络规划中有重要应用。', '#include <vector>\nusing namespace std;\n\nvoid findCutPoints(int u, int p, vector<vector<int>>& adj,\n    vector<int>& dfn, vector<int>& low, int& timer,\n    vector<bool>& isCut) {\n    dfn[u] = low[u] = ++timer;\n    int children = 0;\n    for (int v : adj[u]) {\n        if (v == p) continue;\n        if (!dfn[v]) {\n            children++;\n            findCutPoints(v, u, adj, dfn, low, timer, isCut);\n            low[u] = min(low[u], low[v]);\n            if (p != -1 && low[v] >= dfn[u]) isCut[u] = true;\n        } else low[u] = min(low[u], dfn[v]);\n    }\n    if (p == -1 && children > 1) isCut[u] = true;\n}', (SELECT id FROM algorithm_categories WHERE name='割点/割边'), 'hard', '图论,Tarjan,割点,割边,桥'),

('二分图判定', '使用染色法（二染色）判断图是否为二分图：对每个未染色的节点进行DFS/BFS，交替染两种颜色。若相邻节点颜色相同则不是二分图。O(V+E)。', '二分图是很多匹配问题的基础结构。常见应用：判断队伍分配是否冲突、课程安排等。', '#include <vector>\nusing namespace std;\n\nbool isBipartite(vector<vector<int>>& adj) {\n    int n = adj.size();\n    vector<int> color(n, -1);\n    for (int i = 0; i < n; i++) {\n        if (color[i] != -1) continue;\n        color[i] = 0;\n        vector<int> q{i};\n        for (int j = 0; j < q.size(); j++) {\n            int u = q[j];\n            for (int v : adj[u]) {\n                if (color[v] == -1) {\n                    color[v] = color[u] ^ 1;\n                    q.push_back(v);\n                } else if (color[v] == color[u])\n                    return false;\n            }\n        }\n    }\n    return true;\n}', (SELECT id FROM algorithm_categories WHERE name='二分图判定'), 'medium', '图论,二分图,染色'),

('二分图最大匹配', '匈牙利算法求二分图的最大匹配（最多的不共享顶点的边数）。每次为未匹配左部点寻找增广路（DFS），找到则匹配数+1。O(VE)。', '广泛应用于配对问题，如任务分配、舞伴配对、课程与教室匹配等。也可以转化为网络流求解。', '#include <vector>\nusing namespace std;\n\nbool dfs(int u, vector<vector<int>>& adj, vector<int>& match,\n         vector<bool>& visited) {\n    for (int v : adj[u]) {\n        if (visited[v]) continue;\n        visited[v] = true;\n        if (match[v] == -1 || dfs(match[v], adj, match, visited)) {\n            match[v] = u;\n            return true;\n        }\n    }\n    return false;\n}\n\nint hungarian(int n, int m, vector<vector<int>>& adj) {\n    vector<int> match(m, -1);\n    int maxMatch = 0;\n    for (int u = 0; u < n; u++) {\n        vector<bool> visited(m, false);\n        if (dfs(u, adj, match, visited)) maxMatch++;\n    }\n    return maxMatch;\n}', (SELECT id FROM algorithm_categories WHERE name='二分图最大匹配'), 'hard', '图论,二分图,匹配,匈牙利算法'),

('欧拉路径/欧拉回路', '欧拉路径：恰好一次经过图中每条边的路径（允许起点≠终点）。欧拉回路：起点=终点的欧拉路径。Hierholzer算法在O(E)时间构造欧拉回路：从任意点DFS，回溯时将边加入路径，最后反转。', '存在条件：无向图的欧拉回路要求所有度数为偶数，欧拉路径要求恰好0或2个奇度点。应用于DNA组装、邮递员问题等。', '#include <vector>\nusing namespace std;\n\nvoid hierholzer(int u, vector<vector<int>>& adj,\n                vector<int>& path) {\n    while (!adj[u].empty()) {\n        int v = adj[u].back();\n        adj[u].pop_back();\n        // 无向图还需删除反向边 adj[v] 中的 u\n        hierholzer(v, adj, path);\n    }\n    path.push_back(u);\n}\n// path需要reverse后才是正确顺序', (SELECT id FROM algorithm_categories WHERE name='欧拉路径/欧拉回路'), 'medium', '图论,欧拉回路,Hierholzer'),

('差分约束系统', '差分约束系统由多个x_j - x_i ≤ w的不等式组成，求一组满足所有约束的解。转化为图论：建边i→j权w，添加超级源点跑SPFA求最长路。若有负环则无解。', '适用于变量间存在大量不等式约束的问题，如任务安排的时间约束、资源分配的限制条件等。', '#include <vector>\n#include <queue>\nusing namespace std;\n\nbool diffConstraint(int n, vector<tuple<int,int,int>>& constraints,\n                    vector<int>& result) {\n    // constraints: (i, j, w) 表示 x_j - x_i <= w\n    // 建边 i -> j 权值 w\n    vector<vector<pair<int,int>>> adj(n + 1); // n+1为超级源点\n    for (auto [i, j, w] : constraints)\n        adj[i].push_back({j, w});\n    for (int i = 0; i < n; i++)\n        adj[n].push_back({i, 0}); // 超级源点\n    // 跑SPFA求最长路（判负环）\n    return true; // 简化：返回是否有解\n}', (SELECT id FROM algorithm_categories WHERE name='差分约束系统'), 'medium', '图论,差分约束,SPFA,不等式');

-- ==================== 动态规划 ====================

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('0/1背包', '有N件物品和容量W的背包，每件物品只能选0次或1次，求最大价值。二维DP可优化为一维，需倒序遍历保证每件物品只选一次。O(NW)。', '最经典的DP问题，广泛出现在竞赛和面试中。掌握0/1背包后，其他背包变体都可以类似推导。', '#include <vector>\nusing namespace std;\n\nint zeroOneKnapsack(vector<int>& weight, vector<int>& value, int W) {\n    vector<int> dp(W + 1, 0);\n    for (int i = 0; i < weight.size(); i++)\n        for (int w = W; w >= weight[i]; w--)\n            dp[w] = max(dp[w], dp[w - weight[i]] + value[i]);\n    return dp[W];\n}', (SELECT id FROM algorithm_categories WHERE name='背包DP'), 'medium', 'DP,背包,0/1背包'),

('完全背包', '每件物品可选无限次，其余同0/1背包。将内层循环从倒序改为正序即可：正序遍历使得同一物品可多次选取。O(NW)。', '适用于物品可重复选取的场景，如硬币找零（每种硬币无限枚）、完全背包变体等。', '#include <vector>\nusing namespace std;\n\nint completeKnapsack(vector<int>& weight, vector<int>& value, int W) {\n    vector<int> dp(W + 1, 0);\n    for (int i = 0; i < weight.size(); i++)\n        for (int w = weight[i]; w <= W; w++)\n            dp[w] = max(dp[w], dp[w - weight[i]] + value[i]);\n    return dp[W];\n}', (SELECT id FROM algorithm_categories WHERE name='背包DP'), 'medium', 'DP,背包,完全背包'),

('多重背包', '每件物品有数量限制c_i个。朴素做法展开为0/1背包O(WΣc_i)，二进制优化：将c_i拆分为1,2,4,...,剩余，转化为O(WΣlog c_i)。', '适用于有数量限制的物品选取问题。二进制优化是竞赛中必须掌握的技巧，可将O(n³)降到O(n²log n)。', '#include <vector>\nusing namespace std;\n\nint multiKnapsack(vector<int>& weight, vector<int>& value,\n                  vector<int>& cnt, int W) {\n    vector<int> dp(W + 1, 0);\n    for (int i = 0; i < weight.size(); i++) {\n        int c = cnt[i];\n        for (int k = 1; c > 0; k <<= 1) {\n            int take = min(k, c);\n            c -= take;\n            int kw = take * weight[i], kv = take * value[i];\n            for (int w = W; w >= kw; w--)\n                dp[w] = max(dp[w], dp[w - kw] + kv);\n        }\n    }\n    return dp[W];\n}', (SELECT id FROM algorithm_categories WHERE name='背包DP'), 'medium', 'DP,背包,多重背包,二进制优化'),

('分组背包', '物品分为若干组，每组最多选一个物品。外层循环遍历组，中层倒序遍历容量，内层遍历组内物品。O(WΣsize_i)。', '适用于有分组限制的选择问题，如选修课（每个类别最多选一门）、装备选择（同类装备最多选一个）。', '#include <vector>\nusing namespace std;\n\nint groupKnapsack(vector<vector<pair<int,int>>>& groups, int W) {\n    // groups[g] = {{weight, value}, ...}\n    vector<int> dp(W + 1, 0);\n    for (auto& g : groups) {\n        for (int w = W; w >= 0; w--) {\n            for (auto& [gw, gv] : g) {\n                if (w >= gw)\n                    dp[w] = max(dp[w], dp[w - gw] + gv);\n            }\n        }\n    }\n    return dp[W];\n}', (SELECT id FROM algorithm_categories WHERE name='背包DP'), 'medium', 'DP,背包,分组背包'),

('区间DP', '以区间长度作为DP阶段，从小到大枚举区间长度进行状态转移。典型问题：石子合并、矩阵链乘、回文串相关等。核心是找区间划分点k，将[i,j]分解为[i,k]和[k+1,j]。', '适用于问题可分解为子区间合并的场景。如回文相关问题、括号匹配、多边形三角剖分等。', '#include <vector>\n#include <algorithm>\nusing namespace std;\n\nint stoneMerge(vector<int>& stones) {\n    int n = stones.size();\n    vector<int> prefix(n + 1, 0);\n    for (int i = 0; i < n; i++) prefix[i + 1] = prefix[i] + stones[i];\n    vector<vector<int>> dp(n, vector<int>(n, 0));\n    for (int len = 2; len <= n; len++) {\n        for (int i = 0; i + len - 1 < n; i++) {\n            int j = i + len - 1;\n            dp[i][j] = INT_MAX;\n            for (int k = i; k < j; k++)\n                dp[i][j] = min(dp[i][j],\n                    dp[i][k] + dp[k+1][j] + prefix[j+1] - prefix[i]);\n        }\n    }\n    return dp[0][n - 1];\n}', (SELECT id FROM algorithm_categories WHERE name='区间DP'), 'medium', 'DP,区间DP'),

('树形DP', '在树结构上进行的DP。以DFS遍历树，在回溯时合并子节点状态计算当前节点状态。经典问题：树的最大独立集、树的重心、树的直径、树上背包等。', '适用于树结构上的最优决策问题。关键：正确定义状态（如选/不选当前节点）和转移方程。', '#include <vector>\nusing namespace std;\n\nvoid treeDP(int u, int p, vector<vector<int>>& adj,\n            vector<int>& val, vector<int>& dp0, vector<int>& dp1) {\n    dp0[u] = 0;        // 不选u\n    dp1[u] = val[u];   // 选u\n    for (int v : adj[u]) {\n        if (v == p) continue;\n        treeDP(v, u, adj, val, dp0, dp1);\n        dp0[u] += max(dp0[v], dp1[v]);\n        dp1[u] += dp0[v];\n    }\n}', (SELECT id FROM algorithm_categories WHERE name='树形DP'), 'medium', 'DP,树形DP,树'),

('数位DP', '数位DP按数位逐位进行DP，通常用来统计满足特定条件的数字个数。状态一般包括当前位数、是否受限（tight）、是否含前导零等。', '典型应用：统计[l,r]范围内不含某数字、数位和满足条件、能被某数整除的数字个数等。', '#include <string>\n#include <cstring>\nusing namespace std;\nusing ll = long long;\n\nll dp[20][2][2];\nstring s;\n\nll dfs(int pos, bool tight, bool started) {\n    if (pos == s.size()) return 1; // 到达末尾\n    if (dp[pos][tight][started] != -1)\n        return dp[pos][tight][started];\n    ll res = 0;\n    int limit = tight ? s[pos] - ''0'' : 9;\n    for (int d = 0; d <= limit; d++) {\n        res += dfs(pos + 1,\n            tight && (d == limit),\n            started || (d != 0));\n    }\n    return dp[pos][tight][started] = res;\n}\n\nll count(ll x) {\n    s = to_string(x);\n    memset(dp, -1, sizeof(dp));\n    return dfs(0, true, false);\n}', (SELECT id FROM algorithm_categories WHERE name='数位DP'), 'hard', 'DP,数位DP,计数'),

('状压DP', '状态压缩DP使用二进制位压缩表示集合状态（如哪些物品已选、哪些位置已占）。通常dp[mask]表示在当前状态下能达到的最优值。状态数2^n。', '适用于n较小（n≤20~24）的集合覆盖、旅行商问题(TSP)、哈密顿路径、分配问题等。', '#include <vector>\nusing namespace std;\n\n// TSP：旅行商问题\nint tsp(vector<vector<int>>& dist) {\n    int n = dist.size();\n    vector<vector<int>> dp(1 << n, vector<int>(n, INT_MAX / 2));\n    dp[1][0] = 0; // 从0出发\n    for (int mask = 1; mask < (1 << n); mask++) {\n        for (int u = 0; u < n; u++) {\n            if (!(mask & (1 << u))) continue;\n            for (int v = 0; v < n; v++) {\n                if (mask & (1 << v)) continue;\n                dp[mask | (1 << v)][v] = min(\n                    dp[mask | (1 << v)][v],\n                    dp[mask][u] + dist[u][v]);\n            }\n        }\n    }\n    int ans = INT_MAX;\n    for (int u = 1; u < n; u++)\n        ans = min(ans, dp[(1 << n) - 1][u] + dist[u][0]);\n    return ans;\n}', (SELECT id FROM algorithm_categories WHERE name='状压DP'), 'hard', 'DP,状压DP,状态压缩,TSP'),

('计数DP', '计数DP用于统计满足条件的方案总数（而非最优值）。通常用dp[i]表示到第i个状态时的方案数，转移时累加而非取max/min。', '适用于求方案数的问题：不同路径数、背包方案数、整数的划分数等。注意结果可能很大需要取模。', '#include <vector>\nusing namespace std;\nconst int MOD = 1e9 + 7;\n\nint countPaths(vector<vector<int>>& grid) {\n    int m = grid.size(), n = grid[0].size();\n    vector<vector<int>> dp(m, vector<int>(n, 0));\n    dp[0][0] = 1;\n    for (int i = 0; i < m; i++) {\n        for (int j = 0; j < n; j++) {\n            if (grid[i][j] == 1) continue; // 障碍物\n            if (i > 0) dp[i][j] = (dp[i][j] + dp[i-1][j]) % MOD;\n            if (j > 0) dp[i][j] = (dp[i][j] + dp[i][j-1]) % MOD;\n        }\n    }\n    return dp[m - 1][n - 1];\n}', (SELECT id FROM algorithm_categories WHERE name='计数DP'), 'medium', 'DP,计数DP,方案数'),

('概率DP', '概率DP计算随机过程中某事件发生的概率或期望值。通常dp[i]表示在状态i下达成目标的概率/期望步数，转移方程基于全概率公式推导。', '典型问题：掷骰子期望步数、游戏通关概率、随机游走问题、最优停止问题等。', '#include <vector>\nusing namespace std;\n\n// 概率DP：掷骰子到达目标位置的期望次数\ndouble expectedSteps(int target) {\n    vector<double> dp(target + 7, 0);\n    for (int i = target - 1; i >= 0; i--) {\n        dp[i] = 1;\n        for (int d = 1; d <= 6; d++)\n            dp[i] += dp[i + d] / 6.0;\n    }\n    return dp[0];\n}', (SELECT id FROM algorithm_categories WHERE name='概率DP'), 'hard', 'DP,概率DP,期望');

-- ==================== 字符串 ====================

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('KMP算法', 'KMP(Knuth-Morris-Pratt)字符串匹配算法通过预处理模式串的next数组（前缀函数），在匹配失败时利用已匹配信息跳过不必要的比较。时间复杂度O(n+m)。', '高效的单模式串匹配算法，广泛应用于文本搜索、DNA序列匹配等。相比暴力O(nm)，KMP在线性时间内完成匹配。', '#include <string>\n#include <vector>\nusing namespace std;\n\nvector<int> computeLPS(string& pat) {\n    int m = pat.size();\n    vector<int> lps(m, 0);\n    for (int i = 1, len = 0; i < m; ) {\n        if (pat[i] == pat[len]) lps[i++] = ++len;\n        else if (len) len = lps[len - 1];\n        else lps[i++] = 0;\n    }\n    return lps;\n}\n\nvector<int> kmp(string& txt, string& pat) {\n    vector<int> lps = computeLPS(pat), res;\n    int n = txt.size(), m = pat.size();\n    for (int i = 0, j = 0; i < n; ) {\n        if (txt[i] == pat[j]) { i++; j++; }\n        if (j == m) { res.push_back(i - j); j = lps[j - 1]; }\n        else if (i < n && txt[i] != pat[j])\n            j ? j = lps[j - 1] : i++;\n    }\n    return res; // 所有匹配起始位置\n}', (SELECT id FROM algorithm_categories WHERE name='KMP算法'), 'medium', '字符串,KMP,匹配'),

('Manacher算法', 'Manacher算法在线性时间O(n)内找出字符串中所有回文子串的半径。核心是利用回文的对称性质减少重复计算，使用#填充统一处理奇偶回文。', '求解最长回文子串的高效算法，比中心扩展法O(n²)和DP法O(n²)都快。也用于回文子串计数等问题。', '#include <string>\n#include <vector>\nusing namespace std;\n\nstring manacher(string& s) {\n    string t = \"#\";\n    for (char c : s) { t += c; t += ''#''; }\n    int n = t.size(), c = 0, r = 0;\n    vector<int> p(n, 0);\n    for (int i = 0; i < n; i++) {\n        int mirr = 2 * c - i;\n        if (i < r) p[i] = min(r - i, p[mirr]);\n        while (i + p[i] + 1 < n && i - p[i] - 1 >= 0\n               && t[i + p[i] + 1] == t[i - p[i] - 1])\n            p[i]++;\n        if (i + p[i] > r) { c = i; r = i + p[i]; }\n    }\n    int maxLen = 0, center = 0;\n    for (int i = 0; i < n; i++)\n        if (p[i] > maxLen) { maxLen = p[i]; center = i; }\n    int start = (center - maxLen) / 2;\n    return s.substr(start, maxLen);\n}', (SELECT id FROM algorithm_categories WHERE name='Manacher算法'), 'medium', '字符串,Manacher,回文');

-- ==================== 数学 ====================

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('埃氏筛', '埃拉托色尼筛在O(n log log n)时间内筛出1到n的所有素数。核心思想：从2开始，将每个素数的倍数标记为合数。实现简单，适合入门。', '适用于n≤10^7的素数筛选。对于更大的n或需要复杂度保证的场景，推荐使用欧拉筛（线性筛）。', '#include <vector>\nusing namespace std;\n\nvector<int> eratosthenes(int n) {\n    vector<bool> isPrime(n + 1, true);\n    isPrime[0] = isPrime[1] = false;\n    for (int i = 2; i * i <= n; i++) {\n        if (isPrime[i]) {\n            for (int j = i * i; j <= n; j += i)\n                isPrime[j] = false;\n        }\n    }\n    vector<int> primes;\n    for (int i = 2; i <= n; i++)\n        if (isPrime[i]) primes.push_back(i);\n    return primes;\n}', (SELECT id FROM algorithm_categories WHERE name='素数筛'), 'easy', '数学,素数,埃氏筛'),

('欧拉筛（线性筛）', '线性筛在O(n)时间内筛出1到n的所有素数。每个合数只被其最小质因子筛掉一次，保证线性复杂度。同时可求出最小质因子和欧拉函数值。', '当n很大（≥10^7）或需要严格O(n)复杂度时推荐使用。可顺手求出每个数的最小质因子，方便快速质因数分解。', '#include <vector>\nusing namespace std;\n\nvector<int> eulerSieve(int n) {\n    vector<int> primes;\n    vector<bool> isPrime(n + 1, true);\n    isPrime[0] = isPrime[1] = false;\n    for (int i = 2; i <= n; i++) {\n        if (isPrime[i]) primes.push_back(i);\n        for (int p : primes) {\n            if (i * p > n) break;\n            isPrime[i * p] = false;\n            if (i % p == 0) break; // 保证最小质因子筛掉\n        }\n    }\n    return primes;\n}', (SELECT id FROM algorithm_categories WHERE name='素数筛'), 'medium', '数学,素数,线性筛,欧拉筛'),

('欧拉函数', 'φ(n)表示1到n中与n互质的正整数个数。φ(n)=n×Π(1-1/pi)，pi为n的所有不同质因子。积性函数，可用线性筛批量计算。', '数论基础函数，用于简化模运算，是欧拉定理和RSA加密算法的基础。常用于求解同余方程和模逆元。', 'int phi(int n) {\n    int res = n;\n    for (int i = 2; i * i <= n; i++) {\n        if (n % i == 0) {\n            res = res / i * (i - 1);\n            while (n % i == 0) n /= i;\n        }\n    }\n    if (n > 1) res = res / n * (n - 1);\n    return res;\n}\n\n// 线性筛批量求1~n的欧拉函数\nvector<int> phiSieve(int n) {\n    vector<int> phi(n + 1), primes;\n    vector<bool> isPrime(n + 1, true);\n    phi[1] = 1;\n    for (int i = 2; i <= n; i++) {\n        if (isPrime[i]) { primes.push_back(i); phi[i] = i - 1; }\n        for (int p : primes) {\n            if (i * p > n) break;\n            isPrime[i * p] = false;\n            if (i % p == 0) { phi[i * p] = phi[i] * p; break; }\n            phi[i * p] = phi[i] * (p - 1);\n        }\n    }\n    return phi;\n}', (SELECT id FROM algorithm_categories WHERE name='欧拉函数'), 'medium', '数学,数论,欧拉函数'),

('扩展欧几里得', '扩展欧几里得算法求解ax + by = gcd(a,b)的一组整数解(x,y)。顺带求出gcd。利用辗转相除法的递归结构推导。O(log max(a,b))。', '用于求解线性同余方程ax≡b(mod m)、求模意义下的乘法逆元（当模数不是素数时），以及中国剩余定理。', 'using ll = long long;\n\nll exgcd(ll a, ll b, ll& x, ll& y) {\n    if (!b) { x = 1; y = 0; return a; }\n    ll d = exgcd(b, a % b, y, x);\n    y -= a / b * x;\n    return d;\n}\n\n// 求a在模m下的逆元（需gcd(a,m)=1）\nll modInv(ll a, ll m) {\n    ll x, y;\n    exgcd(a, m, x, y);\n    return (x % m + m) % m;\n}', (SELECT id FROM algorithm_categories WHERE name='扩展欧几里得'), 'medium', '数学,数论,exgcd,逆元'),

('中国剩余定理(CRT)', 'CRT求解同余方程组 x≡r_i (mod m_i)，其中m_i两两互质。公式：x=Σr_i * M_i * inv(M_i)，其中M=Πm_i，M_i=M/m_i，inv为M_i模m_i的逆元。', '适用于同余方程组求解，如"物不知数"问题。当m_i不互质时需使用扩展CRT（合并方程）。', 'using ll = long long;\n\nll crt(vector<ll>& r, vector<ll>& m) {\n    ll M = 1, ans = 0, n = r.size();\n    for (ll mi : m) M *= mi;\n    for (int i = 0; i < n; i++) {\n        ll Mi = M / m[i];\n        ll inv = modInv(Mi, m[i]);\n        ans = (ans + r[i] * Mi % M * inv) % M;\n    }\n    return (ans + M) % M;\n}', (SELECT id FROM algorithm_categories WHERE name='中国剩余定理'), 'hard', '数学,数论,CRT,同余'),

('快速幂', '快速幂利用指数的二进制分解将幂运算从O(n)优化到O(log n)。a^n：n为偶数时同a^(n/2)自乘，n为奇数时多乘一个a。常配合取模解决指数爆炸问题。', '广泛用于大数幂运算取模，是很多数学算法（如模逆元、组合数、矩阵快速幂）的基础组件。', 'using ll = long long;\n\nll quickPow(ll a, ll b, ll mod) {\n    ll res = 1; a %= mod;\n    while (b) {\n        if (b & 1) res = (res * a) % mod;\n        a = (a * a) % mod;\n        b >>= 1;\n    }\n    return res;\n}', (SELECT id FROM algorithm_categories WHERE name='快速幂/矩阵快速幂'), 'easy', '数学,快速幂,位运算'),

('矩阵快速幂', '矩阵快速幂将快速幂的乘法推广到矩阵乘法。用于在O(k³ log n)时间内求解线性递推数列的第n项（如斐波那契数列），k为矩阵阶数。', '适用于线性递推数列加速计算（如斐波那契第10^18项）、图论中的路径计数问题等。', '#include <vector>\nusing namespace std;\nusing ll = long long;\nusing Matrix = vector<vector<ll>>;\nconst int MOD = 1e9 + 7;\n\nMatrix matMul(Matrix& A, Matrix& B) {\n    int n = A.size();\n    Matrix C(n, vector<ll>(n, 0));\n    for (int i = 0; i < n; i++)\n        for (int k = 0; k < n; k++)\n            if (A[i][k])\n                for (int j = 0; j < n; j++)\n                    C[i][j] = (C[i][j] + A[i][k] * B[k][j]) % MOD;\n    return C;\n}\n\nMatrix matPow(Matrix A, ll b) {\n    int n = A.size();\n    Matrix res(n, vector<ll>(n, 0));\n    for (int i = 0; i < n; i++) res[i][i] = 1;\n    while (b) {\n        if (b & 1) res = matMul(res, A);\n        A = matMul(A, A); b >>= 1;\n    }\n    return res;\n}', (SELECT id FROM algorithm_categories WHERE name='快速幂/矩阵快速幂'), 'medium', '数学,矩阵快速幂,递推'),

('组合数取模', '计算C(n,k) mod p的方法取决于p的性质。p为素数时用阶乘逆元O(1)查询；p较小n很大时用Lucas定理；p非素数时用扩展Lucas。', '竞赛中的常见需求。注意根据模数大小和性质选择合适方法，预处理阶乘和逆元后单次查询O(1)。', 'using ll = long long;\nconst int MOD = 1e9 + 7, MAXN = 1e6;\nvector<ll> fact(MAXN + 1), invFact(MAXN + 1);\n\nll quickPow(ll a, ll b) {\n    ll res = 1;\n    while (b) {\n        if (b & 1) res = res * a % MOD;\n        a = a * a % MOD; b >>= 1;\n    }\n    return res;\n}\n\nvoid precompute() {\n    fact[0] = 1;\n    for (int i = 1; i <= MAXN; i++) fact[i] = fact[i-1] * i % MOD;\n    invFact[MAXN] = quickPow(fact[MAXN], MOD - 2);\n    for (int i = MAXN - 1; i >= 0; i--)\n        invFact[i] = invFact[i+1] * (i + 1) % MOD;\n}\n\nll C(int n, int k) {\n    if (k < 0 || k > n) return 0;\n    return fact[n] * invFact[k] % MOD * invFact[n-k] % MOD;\n}', (SELECT id FROM algorithm_categories WHERE name='组合数取模'), 'medium', '数学,组合数,模运算,逆元');

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('容斥原理', '容斥原理统计多个集合并集的大小的精确方法：|A∪B∪C|=Σ|A|-Σ|A∩B|+Σ|A∩B∩C|-...，正负交替。用于处理"至少满足一个条件"的计数问题。', '适用于涉及多个条件且直接计算困难的计数问题，如计算1~n中能被若干素数整除的数的个数、错排问题等。', 'using ll = long long;\n// 1~n中能被arr中某数整除的数的个数\nll countDivisible(ll n, vector<ll>& arr) {\n    int m = arr.size();\n    ll ans = 0;\n    for (int mask = 1; mask < (1 << m); mask++) {\n        ll lcm = 1; int bits = 0;\n        for (int i = 0; i < m; i++) {\n            if (mask & (1 << i)) {\n                bits++;\n                lcm = lcm / __gcd(lcm, arr[i]) * arr[i];\n                if (lcm > n) break;\n            }\n        }\n        if (lcm > n) continue;\n        ans += (bits & 1 ? 1 : -1) * (n / lcm);\n    }\n    return ans;\n}', (SELECT id FROM algorithm_categories WHERE name='容斥原理'), 'medium', '数学,容斥原理,组合数学'),

('博弈论基础', '博弈论研究多个参与者在策略互动中的决策。算法竞赛常见：Nim游戏（异或和）、SG函数（有向图游戏的等价分析）、巴什博弈等。', '适用于双方轮流操作、信息完全透明的游戏问题。SG函数可将复杂游戏分解为子游戏的异或和，是解决公平组合游戏的关键工具。', '// Nim游戏：n堆石子，每次从一堆取任意数\nbool nimGame(vector<int>& piles) {\n    int xorSum = 0;\n    for (int p : piles) xorSum ^= p;\n    return xorSum != 0; // 非零则先手必胜\n}\n\n// SG函数打表\nvector<int> sg(n + 1, 0);\nfor (int i = 1; i <= n; i++) {\n    set<int> reachable;\n    for (int move : getMoves(i))\n        reachable.insert(sg[i - move]);\n    while (reachable.count(sg[i])) sg[i]++;\n}', (SELECT id FROM algorithm_categories WHERE name='博弈论'), 'medium', '数学,博弈论,Nim,SG函数'),

('高斯消元', '高斯消元将线性方程组转化为上三角矩阵进行求解。通过行变换（交换行、行倍乘、行加减）消去变量。复杂度O(n³)。', '用于解线性方程组、矩阵求秩、求逆矩阵、求解期望DP中的方程组等。是线性代数在算法中的核心实现。', '#include <vector>\n#include <cmath>\nusing namespace std;\n\nconst double EPS = 1e-9;\n\nvector<double> gauss(vector<vector<double>> a, vector<double> b) {\n    int n = a.size();\n    for (int col = 0, row = 0; col < n && row < n; col++) {\n        int pivot = row;\n        for (int i = row + 1; i < n; i++)\n            if (fabs(a[i][col]) > fabs(a[pivot][col])) pivot = i;\n        if (fabs(a[pivot][col]) < EPS) continue;\n        swap(a[row], a[pivot]); swap(b[row], b[pivot]);\n        for (int i = row + 1; i < n; i++) {\n            double factor = a[i][col] / a[row][col];\n            for (int j = col; j < n; j++) a[i][j] -= factor * a[row][j];\n            b[i] -= factor * b[row];\n        }\n        row++;\n    }\n    // 回代\n    vector<double> x(n, 0);\n    for (int i = n - 1; i >= 0; i--) {\n        x[i] = b[i];\n        for (int j = i + 1; j < n; j++) x[i] -= a[i][j] * x[j];\n        if (fabs(a[i][i]) > EPS) x[i] /= a[i][i];\n    }\n    return x;\n}', (SELECT id FROM algorithm_categories WHERE name='高斯消元'), 'hard', '数学,线性代数,高斯消元,方程组'),

('线性基', '线性基是处理异或问题的数据结构。给定一组数，线性基可以表示这组数能异或出的所有值。支持插入O(log V)、查询最大值、查询第k小等操作。', '适用于最大异或子集、异或方程组求解、图上异或路径（异或生成树）等涉及异或的问题。', '#include <vector>\nusing namespace std;\nusing ll = long long;\nconst int MAX_BIT = 60;\n\nstruct LinearBasis {\n    vector<ll> basis;\n    LinearBasis() : basis(MAX_BIT + 1, 0) {}\n    void insert(ll x) {\n        for (int i = MAX_BIT; i >= 0; i--) {\n            if (!(x >> i & 1)) continue;\n            if (!basis[i]) { basis[i] = x; return; }\n            x ^= basis[i];\n        }\n    }\n    ll maxXor() {\n        ll res = 0;\n        for (int i = MAX_BIT; i >= 0; i--)\n            if ((res ^ basis[i]) > res)\n                res ^= basis[i];\n        return res;\n    }\n    bool exists(ll x) {\n        for (int i = MAX_BIT; i >= 0; i--)\n            if (x >> i & 1) x ^= basis[i];\n        return x == 0;\n    }\n};', (SELECT id FROM algorithm_categories WHERE name='线性基'), 'hard', '数学,线性基,异或,线性代数');

-- ==================== 思维技巧 ====================

INSERT INTO `algorithms` (`title`, `description`, `usage_intro`, `cpp_template`, `category_id`, `difficulty`, `tags`) VALUES
('模拟', '模拟算法严格按照问题描述逐步执行操作，不涉及复杂的算法优化。核心在于仔细阅读题目、正确理解规则、注意边界条件和特殊情况。', '适用于操作规则明确、主要考察实现能力而非算法优化的问题。竞赛中模拟题常因细节多、易出错而成为拉分题。', '// 大数加法模拟\n#include <string>\nusing namespace std;\n\nstring addStrings(string a, string b) {\n    int i = a.size() - 1, j = b.size() - 1, carry = 0;\n    string res;\n    while (i >= 0 || j >= 0 || carry) {\n        int sum = carry;\n        if (i >= 0) sum += a[i--] - ''0'';\n        if (j >= 0) sum += b[j--] - ''0'';\n        res += (sum % 10) + ''0'';\n        carry = sum / 10;\n    }\n    reverse(res.begin(), res.end());\n    return res;\n}', (SELECT id FROM algorithm_categories WHERE name='模拟'), 'easy', '思维,模拟,实现'),

('构造', '构造题要求根据特定条件构造出一组合法的解（序列、图、矩阵等）。通常没有固定算法模板，需要分析问题的性质和必要条件，再设计构造方案。', '构造题常见于竞赛，如构造符合度数序列的图、构造满足特定条件的排列或矩阵等。关键是分析必要条件是否充分。', '// 构造一个和为S的长度为N的正整数数组\#include <vector>\nusing namespace std;\n\nvector<int> constructArray(int n, int S) {\n    if (S < n) return {}; // 无解\n    vector<int> res(n, 1);\n    S -= n;\n    for (int i = 0; i < n && S > 0; i++) {\n        int add = min(S, INT_MAX / 2);\n        res[i] += add; S -= add;\n    }\n    return res;\n}', (SELECT id FROM algorithm_categories WHERE name='构造'), 'medium', '思维,构造'),

('逆向思维', '逆向思维从问题的反面或目标出发倒推求解。常见的套路：从终点向起点递推、考虑"不满足条件"的情况再用总数减去、倒序处理操作等。', '适用于正着做复杂的场景，如逆向DP（从终点推到起点）、补集转化（总数-不合条件数）、反悔贪心、逆向并查集等。', '// 逆向并查集：删除边改为加边\n// 先处理所有不会被删的边，再倒序将删除操作变为添加\nstruct Operation { int type, u, v; };\nDSU dsu(n);\n// 加入所有最终仍存在的边\n// 倒序遍历操作：type==delete时变为unite(u,v)\nfor (int i = ops.size() - 1; i >= 0; i--) {\n    if (ops[i].type == DELETE)\n        dsu.unite(ops[i].u, ops[i].v);\n}', (SELECT id FROM algorithm_categories WHERE name='逆向思维'), 'medium', '思维,逆向思维,补集转化');

-- ============================================
-- 全部算法数据插入完毕（共68个算法）
-- ============================================




